### ISSUE TITLE
能解释下工作原理么？

### ISSUE THREAD

**Issue by GoogleCodeExporter** [greensea/sshband#6]
```

RT
```

Original issue reported on code.google.com by `kofreestyler` on 28 Apr 2012 at 3:00

**Comment by greensea** [comment]
1. 通过 libpcap 直接抓取数据包，把 22 端口上的流量都认为是 SSH 流量，然后按照客户端 IP 和端口号对流进行区分；
2. 从操作系统中抓取网络端口信息，建立在第一步中分析出的流与登录用户的对应关系
3. 然后我们就能知道哪个用户使用了多少流量了
